### ISSUE TITLE
Not all motivation/actualization edges are shown.

### ISSUE THREAD

**Issue by svwilke** [cartisan/little_red_hen#1]
Most notably, those edges of type motivation or actualization between two (temporally) subsequent vertices don't (always) show.

**Comment by svwilke** [comment]
Problem: not all motivation and actualization edges exist!
This is caused by the graph not being able to contain two edges with the same source and destination. Because of that, the temporal edge stops us from adding any other edges in that place.

**Comment by cartisan** [comment]
That is an interesting limitation. I see JUNG2 also provides the class `edu.uci.ics.jung.graph.DirectedSparseMultigraph`, try to extend that with `PlotDirectedSparseGraph`. I would predict this should help with duplicate edges.

**Comment by svwilke** [comment]
Thanks! This immediately fixed the problem.
